### ISSUE TITLE
Node-Red example

### ISSUE THREAD

**Issue by stubby-phillips** [atsage/node-red-contrib-LCD20x4-I2C#1]
Example flow.
[lcd20x4-i2cDisplayExample.zip](https://github.com/atsage/node-red-contrib-LCD20x4-I2C/files/2566315/lcd20x4-i2cDisplayExample.zip)

**Comment by asage-me** [comment]
Thanks for posting!  I did make a mistake in the docs...the node is looking for msg.payload.msgs not msg.msgs.  Just a suggestion, you can also skip the JSON node by setting the values as an object:

```
msg.payload = {
	msgs:[
		{
			msg:sString01,
			pos:iPos01,
			center:bCenter01
		},
		{
			msg:sString02,
			pos:iPos02,
			center:bCenter02
		},
		{
			msg:sString03,
			pos:iPos03,
			center:bCenter03
		},
		{
			msg:sString04,
			pos:iPos04,
			center:bCenter04
		}
	]
};
```

**Comment by asage-me** [comment]
I fixed the docs and uploaded your example (with the JSON node removed) [here](https://flows.nodered.org/flow/611699c1c6e6b90f6100b0ab2574fc0d) for easier visibility.

**Comment by stubby-phillips** [comment]
Thanks again, much neater.
