### ISSUE TITLE
Corrupt LCD output

### ISSUE THREAD

**Issue by mick-lan** [atsage/node-red-contrib-LCD20x4-I2C#11]
I am using this on a pi 4. I am gathering data from some temperature sensors. making calcs on the data then showing the results on an LCD20x4 display. This is happening every 5 seconds. Everything works fine, then every so often the screen display becomes corrupted. This can be after 4 hours or longer. The screen either shows blank of will show corrupt data for a fraction of a second then blank screen for the rest of the 5 second. 
I have tried this on other micros pi2, and have changed the LCD and shift register. Again same result.
I then tried to filter the data prior to it being sent to the LCD node. My thought was that a corrupt calculation was creating a string longer than 20 characters. My check was to check the length of the string prior to sending and if greater than 20, send a blank screen.
I then tried to send a blank screen every say 3 minutes, to create a reset, but it stays corrupt.
The rest of the program runs fine, I can view the results via dashboard output over wifi.
Any ideas? Is it possible to reset during a program?

**Comment by asage-me** [comment]
I have actually been seeing something very similar on my Pi 3's that have been working for ages.  I think something has been updated with the kernel, node.js, or node-red recently but I have no idea where the issue is.  I've been having this problem for about a year now.  Once I get this issue I have to completely power down the pi and the screen for it to communicate again (possibly just the screen would fix it but it's sealed in a box).  Is this the case for you as well?  It's almost like the screen is getting something invalid and locking up.  I did a kernel update with `sudo rpi-update` and that seemed to help but I see that someone has reset the pi last Saturday so it's probably still having issues... 

Both of the systems below use identical hardware.  The one that has been locking up has had every bit of hardware replaced except the SD card.  Do you have anything similar and/or could you try the versions listed for the one that works?

Here is a system that works flawlessly:
16 Oct 08:04:43 - [info] Node-RED version: v0.19.5
16 Oct 08:04:43 - [info] Node.js  version: v8.14.0
16 Oct 08:04:43 - [info] Linux 4.14.79-v7+ arm LE

And on a system that locks up constantly:
16 Oct 08:06:13 - [info] Node-RED version: v1.1.3
16 Oct 08:06:13 - [info] Node.js  version: v12.18.4
16 Oct 08:06:13 - [info] Linux 5.4.65-v7+ arm LE

**Comment by asage-me** [comment]
I just had a thought, the python libraries I use haven't been updated in the package (or in source) since I released it https://github.com/sweetpi/python-i2c-lcd  I'll try to find a new python 3 library and see if that makes a difference.

**Comment by mick-lan** [comment]
The only way I can get the system running again is to reboot the pi. Node red is set to auto run. The node red package I am using is v1.0.6. I am not sure where I find the Node.js version or Linux info. I am new to programming so I am not sure how I find the different version or try them. I will investigate.

**Comment by asage-me** [comment]
With my issue a reboot actually doesn't fix it.  You can get the versions numbers by manually running node-red.  Log in with SSH or terminal and issue the command `node-red` and it should be the first 3 lines that come up.  As for installing the specific versions:

This will get you the kernel version I'm on, however, I'm not sure if it will downgrade a higher version.  I haven't tried this.
sudo rpi-update 2267b322afdb18b4abf9603fea836916190b1b5d

node.js, use nvm
https://phoenixnap.com/kb/install-latest-node-js-and-nmp-on-ubuntu

node-red
npm install -g --unsafe-perm node-red@0.19.5

**Comment by mick-lan** [comment]
Sorry for the delay in getting back. The project is currently running on pi2 and it's a bit of a carthorse.
The version I am running is:-
16 Oct 14:49:44 - [info] Node-RED version: v1.0.6
16 Oct 14:49:44 - [info] Node.js  version: v12.16.2
16 Oct 14:49:44 - [info] Linux 4.19.118+ arm LE
The kernel version install seemed to go ok. The install to 0.19.5 came up with a lot of issues. With it being on pi2 it has wireless dongle and has been a little problematic, and it seems to be playing up now. I have lost comms. Thanks for the help so far, I will persevere, but I need to go out now.

**Comment by mick-lan** [comment]
As I said lots of errors with the install to 0.19.5
Version now 
16 Oct 18:52:15 - [info] Node-RED version: v1.0.6
16 Oct 18:52:15 - [info] Node.js  version: v12.16.2
16 Oct 18:52:15 - [info] Linux 4.14.79+ arm LE
So something has happened on the Linux, but issues with node.js and node red.
i will leave it running to see if the Linux change has any effect on the LCD screen

**Comment by asage-me** [comment]
Awesome, let me know how that goes.  If it works now it must be node.js or node-red.

**Comment by mick-lan** [comment]
It's still going. But it is intermittent on when it fails, so i will keep on going. I'm of a different view on the possible problem as the only version difference is changing the Linux 4.19.118 to Linux 4.14.79. I won't get into that now, lets just confirm it keeps working.

**Comment by Barabba11** [comment]
I have corrupted LCD too after some time, I don't know what it depends about, but a reload of the flow (which "resets" somehow or initialize the LCD) fixs the problem.
It was always that with old and new NR versions, running on PI3
Maybe reinizializing the LCD once a week may fix the problem, I have to implement it somehow. If there will be new versions of the module (maybe compiled with new python) I'll be glad to test

**Comment by mick-lan** [comment]
its failed. Flash of corrupt data then blank screen for the rest of the 5 second cycle. Any idea how to get back to  Node.js version: v8.14.0? I will change the micro back to pi4 and retry the node red change.

**Comment by mick-lan** [comment]
Well I changed back to pi4 (its quicker to try things out). Got into a bit of a mess trying to load old versions. Nvm seems to cause lots of warnings and problems, so in the end I have disabled it. I noted that Node red and node.js have new versions. So I am now running on these:- 
18 Oct 10:22:12 - [info] Node-RED version: v1.2.1
18 Oct 10:22:12 - [info] Node.js  version: v12.19.0
18 Oct 10:22:12 - [info] Linux 4.19.118-v7l+ arm LE
Been running for 12 hours

**Comment by mick-lan** [comment]
Afraid its failed again. I am now running a python program to confirm if this is a node red issue.

**Comment by mick-lan** [comment]
Python failed. So totally confused now.
The system was running on an arduino Mega 2560 for about 3 years and didn't miss a beat.  I fancied using wifi and decided to try with pi and node red. Worked great on wifi output and gave LCD output with the issues noted. I have swapped the pi, LCD and shift register. So I need to go away and have a good investigation. Thanks for the help provided, I will update when I find out what is happening.

**Comment by Barabba11** [comment]
as I remember 2560 uses 5V outputs, while raspberry 3,3. Are you using a line voltage adaptor? Have you inserted pullup resistors in the end of the line? You maybe experiencing hw problems on I2C bus

**Comment by mick-lan** [comment]
I have been calling it a shift register, but its a Logic Level Converter. As far as I'm aware it changes the pi 3.3v to 5v. I have not used pull up resisters as I thought the converter handled everything. But my next stage was to refit the arduino to confirm a working state.

**Comment by Barabba11** [comment]
no, the I2C bus should be pulled up, depending on the number of devices, but two 2,2k resistor on both SDA and SCL lines can do the job.

**Comment by mick-lan** [comment]
[https://tutorials-raspberrypi.com/control-a-raspberry-pi-hd44780-lcd-display-via-i2c/] This is the web site and components i have used.

**Comment by Barabba11** [comment]
this module has 10k resistors, it depends how long is your line too, in my opinion this is really high value, they suggest 1/10 of it, 1k

**Comment by mick-lan** [comment]
Length of wire is less than i metre. My problem is that every few hours I end up with a corrupted LCD display. The control is in the loft , so access is not easy. So my way of resetting is to communicate with the pi via VNC and send a reboot instruction. Obviously stopping the LCD freezing is the goal, but a reset about every hour within the program would be a major improvement.

**Comment by Barabba11** [comment]
you have hardware problem in my opinion, I suggested you what you would try, I?ll not add more lines to this topic

**Comment by mick-lan** [comment]
Ok, I appreciate your input. There are lots of these logic level converters out there, i will monitor to see if other people are having a problem. Again thanks

**Comment by Barabba11** [comment]
go to shop and buy resistors and install them next to lcd before asking half world how to solve your problem

**Comment by mick-lan** [comment]
Changed the Logic level converter and its now working. Been OK for about a week. Thanks for all the help. It would be nice to send a reset without having to power down

**Comment by Barabba11** [comment]
It's probably just a question of pull up 3
Resistors, probably the new one has lower ones embedded
