### ISSUE TITLE
I'm a newbie! ANd without an example I have difficulties, thanks for help

### ISSUE THREAD

**Issue by Barabba11** [atsage/node-red-contrib-LCD20x4-I2C#2]
Hi! I tried to write something using iniect node, this:
msg.payload = {
msgs: [
{
msg: "string",
pos: 1,
center: "0"
},
{
msg: "string",
pos: 1,
center: "1"
},
{
msg: "string",
pos: 1,
center: "1"
},
{
msg: "string",
pos: 1,
center: "0"
}
]
};
I tried string, global, JSON, etc. Nothing on display (it works because it appeared SYSTEM START UP) about my messages. I tried also to short it somehow, removing some pharentesis, nothing, what I should send to LCD node? Thank you
Sorry, without a real example I can't got your instructions..

**Comment by Barabba11** [comment]
With string I always have a "msgs Value Not Defined", with Global I have an "OK" but nothing happen on display

**Comment by Barabba11** [comment]
[error] msgs Value not Defined: msg.payload = {     msgs: [         {             msg: "string",             pos: 1,             center: "0"         },         {             msg: "string",             pos: 1,             center: "1"         },         {             msg: "string",             pos: 1,             center: "1"         },         {             msg: "string",             pos: 1,             center: "0"         }     ] };
10 Jan 05:43:32 - [error] Error Sending Message to LCD - See Error Above

**Comment by Barabba11** [comment]
THanks to a good friend I arranged it creating a function who send the proper string. By the way the "center boolean sent as a string" not working

msg.payload = {msgs: [{msg: "string1",pos: 1,center: "0"},{msg: "string2",pos: 3,center: "1"},{msg: "sting3",pos: 1, center: "1"},{msg: "string4",pos: 1,center: "0"}]};
return msg;

**Comment by asage-me** [comment]
Hi,

Center is a boolean value (true/false).  I'll update it to accept 0/1 as that is also be valid.  For now, try this:

```
msg.payload = {
    msgs: [
        {
            msg: "This",
            pos: 1,
            center: false
        },
        {
            msg: "is",
            pos: 2
        },
        {
            msg: "a",
            center: true
        },
        {
            msg: "message",
            pos: 10
        }
    ]
};
```

**Comment by Barabba11** [comment]
Works, thank you! 
Kindly another question, how can I print strings/variables? Is it possible?
Thanks

**Comment by asage-me** [comment]
sure...in a function node use something like this:

```
var somevariable = "variable test";

msg.payload = {
    msgs: [
        {
            msg: "This",
            pos: 1,
            center: false
        },
        {
            msg: "is",
            pos: 2
        },
        {
            msg: "a",
            center: true
        },
        {
            msg: somevariable,
            pos: 10
        }
    ]
};
```

**Comment by Barabba11** [comment]
perfect
