### ISSUE TITLE
i2c adress option

### ISSUE THREAD

**Issue by petrosyanmg** [atsage/node-red-contrib-LCD20x4-I2C#3]
Hi!
I have 20x4 lcd with PCF8574AT i2c driver which default adress (without jumpers) 0x3F insted of 0x27 like PCF8574T.
I spend some time to find & change adress in lcddriver.py to make it work.
Please put this info in README.md. 
![a0a1a2_1](https://user-images.githubusercontent.com/34919427/51302604-ef36fc80-1a43-11e9-857e-32298e372ed4.jpg)

**Comment by asage-me** [comment]
Did you find it?  I will put it on my list of things to do to add a selectable address in the config node.

**Comment by petrosyanmg** [comment]
Yes, I did. Thank you, you doing a good job!

**Comment by asage-me** [comment]
Fixed with c9eecd9

**Comment by asage-me** [comment]
@petrosyanmg pushed fix to npm
