### ISSUE TITLE
Error on boot?

### ISSUE THREAD

**Issue by Barabba11** [atsage/node-red-contrib-LCD20x4-I2C#4]
I'm figuring out to solve a problem, seldom I see this message in debug window:
4/2/2019, 13:49:24node: a0019baf.2b4678
msg : error
"Error: EBADF, Bad file descriptor"
I can click on node: a0019baf.2b4678 but it doesn't select any node in the flow, maybe is it a subflow of your module?
At startup I have:
6 Feb 19:54:41 - [info] Starting flows
pi : TTY=unknown ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/python -u /home/pi/.node-red/node_modules/node-red-contrib-lcd20x4-i2c/LCD20x4-I2C/lcd20x4_i2c.py writelcd 20x4 2
pam_unix(sudo:session): session opened for user root by (uid=0)

Is it ok to have it?
I'm not accusing your module, but since I have this in the startup maybe it can be connected to the EBADF, Bad file descriptor. The error is too seldom to understand disabling your module if it is connected to it. Thank you for support

**Comment by asage-me** [comment]
I just saw your issue now.  Are you still getting the error "Error: EBADF, Bad file descriptor"?  If you go to your admin dashboard and press ctrl+f and type in a0019baf.2b4678 what node comes up?
