### ISSUE TITLE
Afer updating NR to 0.20 doesn't work!

### ISSUE THREAD

**Issue by Barabba11** [atsage/node-red-contrib-LCD20x4-I2C#5]
Hi, I update it, it works after node red start, if I deploy something it locks on System Start UP, I need to stop and start Node red to see LCD working (( 
It shows OK in Node red

16 Apr 14:42:17 - [info] Node-RED version: v0.20.5
16 Apr 14:42:17 - [info] Node.js  version: v10.15.3
16 Apr 14:42:17 - [info] Linux 4.14.98-v7+ arm LE

**Comment by Barabba11** [comment]
Sometimes it works, I can't figure out why,

**Comment by Barabba11** [comment]
Sorry for opn this, it doesn't depend on you but from the ADC converter module that frozen someties

**Comment by asage-me** [comment]
No problem.  So you got it figured out now?

**Comment by Barabba11** [comment]
The LCD is connected after ADC, the ADC has internal timer that every 300ms pulls an output, I filter it with a function and send it to your module.
Your module shows System start up only, it mean it doesn't have any message input
