### ISSUE TITLE
LCD view can go corrupted

### ISSUE THREAD

**Issue by Barabba11** [atsage/node-red-contrib-LCD20x4-I2C#7]
Hi mate, I need your help. This case should not appera but eventually it does, for me not the first time, maybe if I send a string with not correct chars or a unfortunate sequence the LCD got corrupted, it needs to be resetted, it looks only a power of does. Maybe there is a command to give LCD to reset itself and its I2C bus (maybe problem can be on LCD chipset, maybe on the I2C translator, I'm checking it). Maybe you can add something to reset the LCD chip? Thank you!

**Comment by Barabba11** [comment]
before LCD goes corrupt I had about 10-15 seconds of long deply and this error
"Error stopping node: Close timed out"
To recover from this I need to stop ad start the NR service, it means there is something happening during the stop and start that not have place after a simple deploy, maybe the reset of the LCD.
Also the other I2C devices work regulary, so I don't think it's a problem cnnected to I2C bus or the translator

**Comment by Barabba11** [comment]
The problem was caused from an abuse of messages sent (for a mistake, every 200ms an object was sent but empty, and every 800ms a good one, now I filtered it better), maybe giving a normal rate of input (about 500ms, not less) the LCD is able to perform a normal reset after deply too.

**Comment by Barabba11** [comment]
yes it auto recovers, anyway still not very clear how it gets corrupted, I'm reading values from ADC and I save them to set.global, on the output of ADC I've a function for manage LCD, it reads back with global get and produce the string, then there is LCD, how data can result corrupted.. I don't know.
`[{"id":"1c081486.9f2cb3","type":"inject","z":"fef64de3.66c588","name":"","topic":"Clock 100s","payload":"0","payloadType":"num","repeat":"0.2","crontab":"","once":true,"onceDelay":0.1,"x":120,"y":540,"wires":[["ad44dd59.600128","a1d30ede.7275e","9f508cc7.ea6d98","6e9268b9.15874"]]},{"id":"6e9268b9.15874","type":"delay","z":"fef64de3.66c588","name":"","pauseType":"delay","timeout":"60","timeoutUnits":"milliseconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":110,"y":380,"wires":[["e86e621c.8bf4"]]},{"id":"e86e621c.8bf4","type":"function","z":"fef64de3.66c588","name":"crea get_status per ADC","func":"var dimezzaADC=global.get('dimezzaADC')|| 0;\ndimezzaADC++; if (dimezzaADC>3) {dimezzaADC=0;} global.set('dimezzaADC',dimezzaADC);\nif (dimezzaADC==3) {msg={topic:\"get_status\"}; return msg;} \n\n","outputs":1,"noerr":0,"x":330,"y":380,"wires":[["fa8a38aa.82a28"]]},{"id":"fa8a38aa.82a28","type":"ncd-ads1115","z":"fef64de3.66c588","name":"ADC 4 canali","connection":"2ab606d1.4ab30a","addr":"74","interval":"0","outputs":5,"output_all":true,"output_mult":"1","channel_1":"4","channel_2":"5","channel_3":"6","channel_4":"7","gain":"0","mode":"1","rate":"0","compMode":"1","compPol":"0","compLat":"0","compQueue":"3","delay":"100","x":390,"y":100,"wires":[["143ee412.ce898c","69555800.b36ea8"],["76299a7.5420ce4"],["17d15c27.14f654"],["d1bb1224.c0a29"],[]]},{"id":"143ee412.ce898c","type":"function","z":"fef64de3.66c588","name":"ADC1","func":"ADC1 = msg.payload.toString();\nglobal.set('ADC1',ADC1);\n","outputs":1,"noerr":0,"x":590,"y":80,"wires":[[]]},{"id":"76299a7.5420ce4","type":"function","z":"fef64de3.66c588","name":"ADC2","func":"ADC2 = msg.payload.toString();\nglobal.set('ADC2',ADC2);\n","outputs":1,"noerr":0,"x":590,"y":140,"wires":[[]]},{"id":"17d15c27.14f654","type":"function","z":"fef64de3.66c588","name":"ADC3","func":"ADC3 = msg.payload.toString();\nglobal.set('ADC3',ADC3);\n","outputs":1,"noerr":0,"x":610,"y":200,"wires":[[]]},{"id":"d1bb1224.c0a29","type":"function","z":"fef64de3.66c588","name":"ADC4","func":"ADC4 = msg.payload.toString();\nglobal.set('ADC4',ADC4);\n\nreturn msg;","outputs":1,"noerr":0,"x":610,"y":260,"wires":[[]]},{"id":"69555800.b36ea8","type":"function","z":"fef64de3.66c588","name":"Gestisci LCD","func":"msga = {};\nvar valoreADC1 = global.get(\"ADC1\");\nvar valoreADC2 = global.get(\"ADC2\");\nvar valoreADC3 = global.get(\"ADC3\");\nvar valoreADC4 = global.get(\"ADC4\");\nmsg = {payload: [valoreADC1,valoreADC2,valoreADC3,valoreADC4]};\n\nvaloreADC1234 = valoreADC1+\" \"+valoreADC2+\" \"+valoreADC3;\nvar Tenda = global.get(\"TendaCamera\");\n\nvar IO0_AStr = global.get(\"IO0_AStr\");\nvar IO0_BStr = global.get(\"IO0_BStr\");\nvar IO0Str= \"A:\"+IO0_AStr+\"B:\"+IO0_BStr;\n\nvar IO1_AStr = global.get(\"IO1_AStr\");\nvar IO1_BStr = global.get(\"IO1_BStr\");\nvar IO1Str= \"A:\"+IO1_AStr+\"B:\"+IO1_BStr;\n\nmsga.payload = {msgs: [{msg: valoreADC1234 , pos:1,},{msg: valoreADC4,pos: 1,},{msg:  IO0Str,pos: 1,},{msg: IO1Str ,pos: 1,}]};\n\nreturn msga;\n","outputs":1,"noerr":0,"x":790,"y":60,"wires":[["826c9f43.97fdc"]]},{"id":"826c9f43.97fdc","type":"LCD20x4-I2C","z":"fef64de3.66c588","name":"","speed":"2","size":"20x4","x":1010,"y":60,"wires":[]},{"id":"2ab606d1.4ab30a","type":"ncd-comm","z":"","name":"We","bus":"i2c-1","commType":"standard","addr":"0","useMux":false,"muxAddr":"112","muxPort":"0"}]`

**Comment by asage-me** [comment]
It looks like you are writing to the display every 0.2 seconds.  The LCD screens I have used can't refresh that fast.  Try something longer like 2 whole seconds.

**Comment by Barabba11** [comment]
In the first function I divided the rate by 4, so it's every 800ms, seems ok! Thank you for answering

**Comment by Barabba11** [comment]
Mate, I would like to ask you help, you always really polite to reply fast, and you developed this module which is able already to intercept the node red "load" and "ulnoad" module commands when for example deploy a new flow, or shutdown service.
Shortly I'm having an issue with Raspberry, I need to introduce a watchdog which will hardware reboot it if something goes wrong, in my case the TCP stack hangs, so I can't do more nothing on Raspberry (I don't have mouse/monitor). The solution is very easy, just kick the watchdog by an echo "." written to the device, I'm doing it on NR flow every 1-2 seconds (I have to do it within 15 seconds), as well there is a written "V" that is able to stop watchdog, it is useful when for example I stop the service and the Rasberry will not reboot..
I would have a module which is able to output an object when NR ask modules to unload, and waiting an object to tell NR that it is succesfully unloaded. In this case (ask for unload) when I stop NR service or deploy again I can stop the watchdog too, NR will wait for the module to unload (I'm sue the command is executed)and only after this NR can go forward. 
Are you interested on this? May I kindly ask you to develope this module?
It should be very easy, it intercept the request of unload, send an object, wait or an onbject to tell NR succesfully unload. Thank you a lot!
